### PR TITLE
Add feedstock info script

### PR DESCRIPTION
**Pull request by mrakitin**
It conveniently prints the following info assuming the current directory is `all_feedstocks` and the `utils` repo is cloned in the parent dir:
```bash
$ python ../utils/feedstocks_info.py
     Name                              Branch       Changed?
---  --------------------------------  -----------  ----------
  0  02-id-six-collection-feedstock    master       False
  1  03-id-hxn-collection-feedstock    master       False
  2  04-bm-xfm-collection-feedstock    master       False
  3  05-id-srx-collection-feedstock    master       False
  4  06-bm-bmm-collection-feedstock    master       False
  5  11-id-chx-collection-feedstock    master       False
  6  amostra-feedstock                 master       False
  7  analysis-feedstock                use-asserts  True
  8  ansiwrap-feedstock                master       False
  9  argh-feedstock                    master       False
 10  asks-feedstock                    master       False
 11  asteval-feedstock                 master       False
 12  attrs-feedstock                   master       False
 13  bluesky-browser-feedstock         master       False
 14  bluesky-feedstock                 master       False
 15  bluesky-kafka-feedstock           master       False
 16  boltons-feedstock                 master       False
 17  caproto-feedstock                 master       False
 18  chxtools-feedstock                master       False
 19  clang_packages-feedstock          master       False
 20  collection-feedstock              master       False
 21  contextvars-feedstock             master       False
 22  curio-feedstock                   master       False
 23  databroker-feedstock              master       False
 24  doct-feedstock                    master       False
 25  dpkt-feedstock                    master       False
 26  eiger-io-feedstock                master       False
 27  epics-base-feedstock              master       False
 28  event-model-feedstock             master       False
 29  fabio-feedstock                   master       False
 30  ffmpeg-feedstock                  master       False
 31  gfortran_impl_osx-64-feedstock    master       False
 32  gfortran_osx-64-feedstock         master       False
 33  gnutls-feedstock                  master       False
 34  grid-strategy-feedstock           master       False
 35  h11-feedstock                     master       False
 36  hdf5-lz4-feedstock                master       False
 37  historydict-feedstock             master       False
 38  hxnfly-feedstock                  master       False
 39  hxntools-feedstock                master       False
 40  icu-feedstock                     master       False
 41  immutables-feedstock              master       False
 42  inflection-feedstock              master       False
 43  intake-bluesky-feedstock          master       False
 44  intake-xarray-feedstock           master       False
 45  ipympl-feedstock                  master       False
 46  isl-feedstock                     master       False
 47  jansson-feedstock                 master       False
 48  kafka-python-feedstock            master       False
 49  kazoo-feedstock                   master       False
 50  lame-feedstock                    master       False
 51  libgfortran-feedstock             master       False
 52  librdkafka-feedstock              master       False
 53  llvm-openmp-feedstock             master       False
 54  llvm-package-feedstock            master       False
 55  lmfit-feedstock                   master       False
 56  lz4-c-feedstock                   master       False
 57  make-feedstock                    master       False
 58  mongoquery-feedstock              master       False
 59  mpi-feedstock                     master       False
 60  mpi4py-feedstock                  master       False
 61  multio-feedstock                  master       False
 62  netifaces-feedstock               master       False
 63  nettle-feedstock                  master       False
 64  nslsii-feedstock                  master       False
 65  openh264-feedstock                master       False
 66  openmpi-mpi-feedstock             master       False
 67  ophyd-feedstock                   master       False
 68  oscars-feedstock                  master       False
 69  outcome-feedstock                 master       False
 70  parsimonious-feedstock            master       False
 71  peakutils-feedstock               master       False
 72  pims-feedstock                    master       False
 73  ppmac-feedstock                   master       False
 74  prettytable-feedstock             master       False
 75  py4xs-feedstock                   master       False
 76  pyepics-feedstock                 master       False
 77  pyfai-feedstock                   master       False
 78  pyfftw-feedstock                  master       False
 79  pyisemail-feedstock               master       False
 80  pykafka-feedstock                 master       False
 81  pykern-feedstock                  master       False
 82  pyolog-feedstock                  master       False
 83  pypdf2-feedstock                  master       False
 84  python-confluent-kafka-feedstock  master       False
 85  pyxrf-feedstock                   master       False
 86  recordwhat-feedstock              master       False
 87  reportlab-feedstock               master       False
 88  rixs-feedstock                    master       False
 89  scikit-beam-feedstock             master       False
 90  scikit-build-feedstock            master       False
 91  silx-feedstock                    master       False
 92  sixtools-feedstock                master       False
 93  slicerator-feedstock              master       False
 94  sniffio-feedstock                 master       False
 95  suitcase-csv-feedstock            master       False
 96  suitcase-json-metadata-feedstock  master       False
 97  suitcase-jsonl-feedstock          master       False
 98  suitcase-mongo-feedstock          master       False
 99  suitcase-msgpack-feedstock        master       False
100  suitcase-specfile-feedstock       master       False
101  suitcase-tiff-feedstock           master       False
102  suitcase-utils-feedstock          master       False
103  super_state_machine-feedstock     master       False
104  textwrap3-feedstock               master       False
105  tifffile-feedstock                master       False
106  tomopy-feedstock                  master       False
107  trio-feedstock                    master       False
108  uncertainties-feedstock           master       False
109  uwsgi-feedstock                   master       False
110  wxmplot-feedstock                 master       False
111  wxutils-feedstock                 master       False
112  x264-feedstock                    master       False
113  xray-vision-feedstock             master       False
114  xraydb-feedstock                  master       False
115  xraylarch-feedstock               master       False
116  xraylib-feedstock                 master       False
117  xrt-feedstock                     master       False
```

### CODE REVIEW

**Comment by mrakitin** [comment]
@thomashopkins32, do you think we can incorporate into your work?

**Comment by thopkins32** [comment]
Sorry, just saw this now. I can add this as an option for `all-feedstocks`. Something like `all-feedstocks info` as another subparser.

**Comment by mrakitin** [comment]
No worries. Yes, I think it's a good option.

**Comment by mrakitin** [comment]
This is implemented via https://github.com/nsls-ii-forge/nsls2forge-utils/pull/18.

**Pull request closed without merging**
